---
title: "R Notebook"
output: html_notebook
---

```{r}
# install.packages("DBI")
# install.packages("RSQLite")

library(DBI)
library(RSQLite)

knitr::opts_chunk$set(echo = TRUE)
```
Create databases
```{r}
#create databse connection
pizza_runnerdb <- dbConnect(RSQLite::SQLite(),'pizza_runnerdb.sqlite')

#drop table if exists
#dbExecute(pizza_runnerdb,"DROP table runners")

#create table - RUNNER
dbExecute(pizza_runnerdb,"CREATE TABLE runners (
  runner_id INTEGER,
  registration_date DATE
)")
```

```{r}
dbGetQuery(pizza_runnerdb,"select * from runners")
```
```{r}
#insert data into a table
dbExecute(pizza_runnerdb,"INSERT INTO runners
  (runner_id, registration_date)
VALUES
  (1, '2021-01-01'),
  (2, '2021-01-03'),
  (3, '2021-01-08'),
  (4, '2021-01-15');")
```
```{r}
# drop table if exists
#dbExecute(pizza_runnerdb,"DROP table customer_orders")

#create table - customer_orders
dbExecute(pizza_runnerdb, "CREATE TABLE customer_orders (
          order_id INTEGER,
          customer_id INTEGER,
  pizza_id INTEGER,
  exclusions VARCHAR(4),
  extras VARCHAR(4),
  order_time TIMESTAMP
)")

dbGetQuery(pizza_runnerdb, "select * from customer_orders")

#insert data into table
dbExecute(pizza_runnerdb,"INSERT INTO customer_orders
  (order_id, customer_id, pizza_id, exclusions, extras, order_time)
VALUES
  ('1', '101', '1', '', '', '2020-01-01 18:05:02'),
  ('2', '101', '1', '', '', '2020-01-01 19:00:52'),
  ('3', '102', '1', '', '', '2020-01-02 23:51:23'),
  ('3', '102', '2', '', NULL, '2020-01-02 23:51:23'),
  ('4', '103', '1', '4', '', '2020-01-04 13:23:46'),
  ('4', '103', '1', '4', '', '2020-01-04 13:23:46'),
  ('4', '103', '2', '4', '', '2020-01-04 13:23:46'),
  ('5', '104', '1', 'null', '1', '2020-01-08 21:00:29'),
  ('6', '101', '2', 'null', 'null', '2020-01-08 21:03:13'),
  ('7', '105', '2', 'null', '1', '2020-01-08 21:20:29'),
  ('8', '102', '1', 'null', 'null', '2020-01-09 23:54:33'),
  ('9', '103', '1', '4', '1, 5', '2020-01-10 11:22:59'),
  ('10', '104', '1', 'null', 'null', '2020-01-11 18:34:49'),
  ('10', '104', '1', '2, 6', '1, 4', '2020-01-11 18:34:49');")
```
```{r}
#drop table if exists
# dbExecute(pizza_runnerdb, "DROP TABLE runner_orders")

dbExecute(pizza_runnerdb, "CREATE TABLE runner_orders (
  order_id INTEGER,
  runner_id INTEGER,
  pickup_time VARCHAR(19),
  distance VARCHAR(7),
  duration VARCHAR(10),
  cancellation VARCHAR(23)
)")

dbGetQuery(pizza_runnerdb,"select * from runner_orders")

#insert data into a table
dbExecute(pizza_runnerdb,"INSERT INTO runner_orders
  (order_id, runner_id, pickup_time, distance, duration, cancellation)
VALUES
(
  '1', '1', '2020-01-01 18:15:34', '20km', '32 minutes', ''),
  ('2', '1', '2020-01-01 19:10:54', '20km', '27 minutes', ''),
  ('3', '1', '2020-01-03 00:12:37', '13.4km', '20 mins', NULL),
  ('4', '2', '2020-01-04 13:53:03', '23.4', '40', NULL),
  ('5', '3', '2020-01-08 21:10:57', '10', '15', NULL),
  ('6', '3', 'null', 'null', 'null', 'Restaurant Cancellation'),
  ('7', '2', '2020-01-08 21:30:45', '25km', '25mins', 'null'),
  ('8', '2', '2020-01-10 00:15:02', '23.4 km', '15 minute', 'null'),
  ('9', '2', 'null', 'null', 'null', 'Customer Cancellation'),
  ('10', '1', '2020-01-11 18:50:20', '10km', '10minutes', 'null');")
```
```{r}
# drop table if exists
#dbExecute(pizza_runnerdb,"DROP table pizza_names")

# create table
dbExecute(pizza_runnerdb,"CREATE TABLE pizza_names (
  pizza_id INTEGER,
  pizza_name TEXT
)")

dbGetQuery(pizza_runnerdb,"select * from pizza_names")

#insert data into a table
dbExecute(pizza_runnerdb,"INSERT INTO pizza_names
  (pizza_id, pizza_name)
VALUES
  (1, 'Meatlovers'),
  (2, 'Vegetarian');")

#---pizza receipes table----
# drop table if exists
#dbExecute(pizza_runnerdb,"DROP table pizza_recipes")

# create table
dbExecute(pizza_runnerdb,"CREATE TABLE pizza_recipes (
  pizza_id INTEGER,
  toppings TEXT
)")

dbGetQuery(pizza_runnerdb,"select * from pizza_recipes")

#insert data into a table
dbExecute(pizza_runnerdb,"INSERT INTO pizza_recipes
  (pizza_id, toppings)
VALUES
  (1, '1, 2, 3, 4, 5, 6, 8, 10'),
  (2, '4, 6, 7, 9, 11, 12');")

#--pizza toppings table ---
# drop table if exists
#dbExecute(pizza_runnerdb,"DROP table pizza_toppings")

# create table
dbExecute(pizza_runnerdb,"CREATE TABLE pizza_toppings (
  topping_id INTEGER,
  topping_name TEXT
)")

dbGetQuery(pizza_runnerdb,"select * from pizza_toppings")

#insert data into a table
dbExecute(pizza_runnerdb,"INSERT INTO pizza_toppings
  (topping_id, topping_name)
VALUES
  (1, 'Bacon'),
  (2, 'BBQ Sauce'),
  (3, 'Beef'),
  (4, 'Cheese'),
  (5, 'Chicken'),
  (6, 'Mushrooms'),
  (7, 'Onions'),
  (8, 'Pepperoni'),
  (9, 'Peppers'),
  (10, 'Salami'),
  (11, 'Tomatoes'),
  (12, 'Tomato Sauce');")
```

INSPECT THE DATA
```{r}
#list all tables found in the database
dbListTables(pizza_runnerdb)
```

```{r}
# for (table in dbListTables(pizza_runnerdb)) {
#   dbGetQuery(pizza_runnerdb, "select * from table")
# }

dbGetQuery(pizza_runnerdb, "select * from runners")
dbGetQuery(pizza_runnerdb, "select * from customer_orders")
dbGetQuery(pizza_runnerdb, "select * from pizza_names")
dbGetQuery(pizza_runnerdb, "select * from pizza_recipes")
dbGetQuery(pizza_runnerdb, "select * from pizza_toppings")
dbGetQuery(pizza_runnerdb, "select * from runner_orders")

```
DATA TRANSFORMATION & CLEANING
runner orders and customer orders has NA
```{r}
#----Course of action to clean customer_orders table ----
# 1. remove null values in exclusions and extras columns and replace with blank space

dbGetQuery(pizza_runnerdb, "update customer_orders SET exclusions = '' WHERE exclusions IS 'null'")
dbGetQuery(pizza_runnerdb, "update customer_orders SET extras = '' WHERE extras IS 'null' or extras IS NULL")
dbGetQuery(pizza_runnerdb, "select * from customer_orders")
```

```{r}
#----Course of action to clean runner_orders table ----
# 1. remove null values in exclusions and extras columns and replace with blank space
dbGetQuery(pizza_runnerdb, "select * from runner_orders")

# dbExecute(pizza_runnerdb, "DROP table runner_orders_temp")

dbGetQuery(pizza_runnerdb, 
           "CREATE TEMP TABLE runner_orders_temp AS
  SELECT 
  order_id, 
  runner_id,  
  CASE
	  WHEN pickup_time LIKE 'null' THEN ' '
	  ELSE pickup_time
	  END AS pickup_time,
  CASE
	  WHEN distance LIKE 'null' THEN ' '
	  WHEN distance LIKE '%km' THEN TRIM(distance, 'km')
	  ELSE distance 
    END AS distance,
  CASE
	  WHEN duration LIKE 'null' THEN ' '
	  WHEN duration LIKE '%mins' THEN TRIM(duration, 'mins')
	  WHEN duration LIKE '%minute' THEN TRIM(duration, 'minute')
	  WHEN duration LIKE '%minutes' THEN TRIM(duration, 'minutes')
	  ELSE duration
	  END AS duration,
  CASE
	  WHEN cancellation IS NULL or cancellation LIKE 'null' THEN ' '
	  ELSE cancellation
	  END AS cancellation
FROM runner_orders")

dbGetQuery(pizza_runnerdb, "select * from runner_orders_temp")
```

Questions - Pizza Metrics
```{r}
#---- 1. How many pizzas were ordered? ----
dbGetQuery(pizza_runnerdb, "SELECT count(order_id) AS pizza_ordered FROM customer_orders")

#---- 2. How many unique customer orders were made?----
dbGetQuery(pizza_runnerdb, "SELECT count(distinct order_id) unique_orders FROM customer_orders")

#---- 3. How many successful orders were delivered by each runner?----
dbGetQuery(pizza_runnerdb, "SELECT runner_id, count(distance) as successful_orders FROM runner_orders_temp 
           WHERE distance != ''
           GROUP BY runner_id")

#----4. How many of each type of pizza was delivered?----
dbGetQuery(pizza_runnerdb, 
           "SELECT c.pizza_id, count(c.pizza_id) as no_of_pizza_delivered
           FROM customer_orders c
           JOIN runner_orders_temp r
           on c.order_id = r.order_id
           WHERE distance != ''
           GROUP BY c.pizza_id
           ")
#---- 5. How many Vegetarian and Meatlovers were ordered by each customer?----
dbGetQuery(pizza_runnerdb,
           "SELECT
           c.customer_id, 
           p.pizza_name, 
           count(p.pizza_name)
           FROM customer_orders c
           JOIN pizza_names p
           on c.pizza_id = p.pizza_id
           GROUP BY c.customer_id, p.pizza_name
           ")
#---- 6. What was the maximum number of pizzas delivered in a single order?----
dbGetQuery(pizza_runnerdb, 
           "WITH df2 AS
           (SELECT c.order_id,
           count(c.pizza_id) AS no_pizzas_ordered
           FROM customer_orders c
           JOIN runner_orders_temp r
           on c.order_id = r.order_id
           WHERE r.distance != ''
           GROUP BY c.order_id
           ) SELECT order_id, max(no_pizzas_ordered) FROM df2")
#---- 7. For each customer, how many delivered pizzas had at least 1 change and how many had no changes?----
dbGetQuery(pizza_runnerdb, 
           "WITH deliverd_pizza AS 
           (SELECT * FROM customer_orders c JOIN runner_orders_temp r ON c.order_id = r.order_id WHERE distance != '')
           select * from deliverd_pizza")
dbGetQuery(pizza_runnerdb, 
           "WITH deliverd_pizza AS 
           (SELECT * FROM customer_orders c JOIN runner_orders_temp r ON c.order_id = r.order_id WHERE distance != '') 
           SELECT customer_id, count(customer_id) AS total_pizza_order,
           SUM(CASE WHEN exclusions != '' OR extras != '' THEN 1 ELSE 0 END) AS atleast_one_change,
           SUM(CASE WHEN exclusions = '' AND extras = '' THEN 1 ELSE 0 END) AS no_change
           FROM deliverd_pizza
           GROUP BY customer_id")

#---- 8. How many pizzas were delivered that had both exclusions and extras?----
dbGetQuery(pizza_runnerdb,
           "WITH delivered_pizzas AS
           (SELECT * FROM customer_orders c JOIN runner_orders_temp r ON c.order_id = r.order_id WHERE distance != '')
           
           select 
           SUM(case when exclusions != '' AND extras != '' then 1 ELSE 0 END) AS PizzasWithBothChanges
           from delivered_pizzas
           ")
#---- 9. What was the total volume of pizzas ordered for each hour of the day?----
dbGetQuery(pizza_runnerdb, "select 
strftime('%H',order_time) AS hour,
count(pizza_id) AS no_of_pizza_ordered
from customer_orders
           group by hour")

#---- 10. What was the volume of orders for each day of the week?----
dbGetQuery(pizza_runnerdb, "SELECT
           strftime('%w', order_time) AS Day,
           count(order_id)
           FROM customer_orders
           GROUP BY Day")
```
B. Runner and Customer Experience
```{r}
# How many runners signed up for each 1 week period? (i.e. week starts 2021-01-01)
dbGetQuery(pizza_runnerdb,
           "SELECT registration_date AS start_date,
           strftime('%W', registration_date) AS WeekNo,
           count(runner_id) AS NoOfRunnersSignUp
           FROM runners
           group by WeekNo")

# 2. What was the average time in minutes it took for each runner to arrive at the Pizza Runner HQ to pickup the order?
#assuming that runner leaves to get the order right after the order is placed.
#find time difference > find avg
dbGetQuery(pizza_runnerdb,
           "select 
           r.runner_id,
           AVG((JULIANDAY(r.pickup_time) - JULIANDAY(c.order_time)) * 3600) AS avgtime_mins
           from customer_orders c
           JOIN runner_orders_temp r
           on c.order_id = r.order_id
           group by r.runner_id")

# 3.Is there any relationship between the number of pizzas and how long the order takes to prepare?
# find no. of pizza and prep.time
# dbGetQuery(pizza_runnerdb,
#            "select")

# 4. What was the average distance travelled for each customer? 
# distance travelled for food to get to them
dbGetQuery(pizza_runnerdb, 
           "SELECT DISTINCT c.customer_id,
           ROUND(AVG(r.distance),2) AS distance_km
           FROM customer_orders c
           JOIN runner_orders_temp r
           on c.order_id = r.order_id
           WHERE r.duration != ''
           GROUP BY c.customer_id")

# 5. What was the difference between the longest and shortest delivery times for all orders?
# join runner-customer > duration difference by order_id
dbGetQuery(pizza_runnerdb,
           "WITH durationByOrder AS (SELECT distinct c.order_id, r.duration
           FROM customer_orders c
           JOIN runner_orders_temp r
           on c.order_id = r.order_id
           WHERE r.duration != ''
           ORDER BY c.order_id)
           
           SELECT MAX(duration) - MIN(duration) AS timeDiff_mins FROM durationByOrder
           ")

# 6. What was the average speed for each runner for each delivery and do you notice any trend for these values?
# avg speed (distance in km/time in hr) by runner > by order id
#---ANALYSIS----
#Runner 1: avg speed vary from 37.5 - 60 km/hr
#Runner 2: avg speed vary from 60 - 93.6 km/hr #very high range. 
#Runner 3: avg speed is 40 km/hr

#---code----
dbGetQuery(pizza_runnerdb, 
           "SELECT 
           r.runner_id,
           c.customer_id,
           c.order_id,
           COUNT(c.order_id) AS pizza_count,
           CAST(r.distance as float) AS distance, 
           (CAST(r.duration AS INTEGER) / 60) AS duration_hr,
           (CAST(r.distance as float)/CAST(r.duration AS INTEGER))*60 AS AvgSpeed_kmPerhr
           FROM customer_orders c
           JOIN runner_orders_temp r
           on c.order_id = r.order_id
           where CAST(r.duration AS INTEGER) != 0
           group by r.runner_id, c.customer_id, c.order_id, r.distance, r.duration
           ")

# 7. What is the successful delivery percentage for each runner?
# group by runner/total successful delivery
dbGetQuery(pizza_runnerdb, "SELECT 
           runner_id,
           round(100*SUM(CASE WHEN CAST(distance as FLOAT) = 0 THEN 0 ELSE 1 END) / COUNT(*),0)
           FROM runner_orders_temp
           GROUP BY runner_id")

```

C. INGREDIENT OPTIMISATION
```{r}
#dbExecute(pizza_runnerdb, "DROP TABLE temp_pizza_recipes")

#create temp_pizza_recipes
dbExecute(pizza_runnerdb, "CREATE TABLE temp_pizza_recipes (
          pizza_id VARCHAR(50),
          toppings VARCHAR(50))
          ")
dbExecute(pizza_runnerdb, "INSERT INTO temp_pizza_recipes
          WITH RECURSIVE split(pizza_id, toppings, str) AS (
           SELECT pizza_id, '', toppings||',' FROM pizza_recipes
           UNION ALL SELECT
           pizza_id,
           SUBSTR(str, 0, instr(str, ',')),
           SUBSTR(str, instr(str, ',') + 1)
           FROM split WHERE str != '')
           
           SELECT pizza_id, toppings
           FROM split
           WHERE toppings != ''
           ORDER BY pizza_id ")

dbGetQuery(pizza_runnerdb, "SELECT * from temp_pizza_recipes")

```

```{r}
# 1. What are the standard ingredients for each pizza?
dbGetQuery(pizza_runnerdb, "WITH toppings AS (
           SELECT tpr.pizza_id, pn.pizza_name, pt.topping_name, tpr.toppings
           FROM temp_pizza_recipes tpr
           JOIN pizza_toppings pt ON tpr.toppings = pt.topping_id
           JOIN pizza_names pn ON tpr.pizza_id = pn.pizza_id
           
           )
           
           SELECT pizza_name, topping_name AS ingredients FROM toppings
           ")

# 2. What was the most commonly added extra?
dbGetQuery(pizza_runnerdb, "select * from customer_orders")
dbExecute(pizza_runnerdb, "
          WITH RECURSIVE split(pizza_id, extras, str) AS (
           SELECT pizza_id, '', extras||',' FROM customer_orders
           UNION ALL SELECT
           pizza_id,
           SUBSTR(str, 0, instr(str, ',')),
           SUBSTR(str, instr(str, ',') + 1)
           FROM split WHERE str != '')
           
           SELECT pizza_id, extras
           FROM split
           WHERE extras != ''
           ORDER BY pizza_id ")
# 3. What was the most common exclusion?
# 4. Generate an order item for each record in the customers_orders table in the format of one of the following:
# 5. Meat Lovers
# 6. Meat Lovers - Exclude Beef
# 7. Meat Lovers - Extra Bacon
# Meat Lovers - Exclude Cheese, Bacon - Extra Mushroom, Peppers
# Generate an alphabetically ordered comma separated ingredient list for each pizza order from the customer_orders table and add a 2x in front of any relevant ingredients
# For example: "Meat Lovers: 2xBacon, Beef, ... , Salami"
# What is the total quantity of each ingredient used in all delivered pizzas sorted by most frequent first?
```

D. PRICING AND RATINGS
```{r}
# If a Meat Lovers pizza costs $12 and Vegetarian costs $10 and there were no charges for changes - how much money has Pizza Runner made so far if there are no delivery fees?
# What if there was an additional $1 charge for any pizza extras?
# Add cheese is $1 extra
# The Pizza Runner team now wants to add an additional ratings system that allows customers to rate their runner, how would you design an additional table for this new dataset - generate a schema for this new table and insert your own data for ratings for each successful customer order between 1 to 5.
# Using your newly generated table - can you join all of the information together to form a table which has the following information for successful deliveries?
# customer_id
# order_id
# runner_id
# rating
# order_time
# pickup_time
# Time between order and pickup
# Delivery duration
# Average speed
# Total number of pizzas
# If a Meat Lovers pizza was $12 and Vegetarian $10 fixed prices with no cost for extras and each runner is paid $0.30 per kilometre traveled - how much money does Pizza Runner have left over after these deliveries?
```

